<!DOCTYPE html>
<html lang="en"><head>
<script src="OSTA5003-project-phase2_Yawei XI_Yifeng LIN_files/libs/clipboard/clipboard.min.js"></script>
<script src="OSTA5003-project-phase2_Yawei XI_Yifeng LIN_files/libs/quarto-html/tabby.min.js"></script>
<script src="OSTA5003-project-phase2_Yawei XI_Yifeng LIN_files/libs/quarto-html/popper.min.js"></script>
<script src="OSTA5003-project-phase2_Yawei XI_Yifeng LIN_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="OSTA5003-project-phase2_Yawei XI_Yifeng LIN_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="OSTA5003-project-phase2_Yawei XI_Yifeng LIN_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="OSTA5003-project-phase2_Yawei XI_Yifeng LIN_files/libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.37">

  <meta name="author" content="Yawei XI (550827289)">
  <meta name="author" content="Yifeng LIN (560316872)">
  <title>Spotify Tracks Genre Classification Approach</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="OSTA5003-project-phase2_Yawei XI_Yifeng LIN_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="OSTA5003-project-phase2_Yawei XI_Yifeng LIN_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="OSTA5003-project-phase2_Yawei XI_Yifeng LIN_files/libs/revealjs/dist/theme/quarto-2740581606dc327e82f18f789b69d8a0.css">
  <link href="OSTA5003-project-phase2_Yawei XI_Yifeng LIN_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="OSTA5003-project-phase2_Yawei XI_Yifeng LIN_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="OSTA5003-project-phase2_Yawei XI_Yifeng LIN_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="OSTA5003-project-phase2_Yawei XI_Yifeng LIN_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Spotify Tracks Genre Classification Approach</h1>
  <p class="subtitle">OSTA5003 Project Presentation</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Yawei XI (550827289) 
</div>
<div class="quarto-title-author-email">
<a href="mailto:yaxi0006@uni.sydney.edu.au">yaxi0006@uni.sydney.edu.au</a>
</div>
</div>
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Yifeng LIN (560316872) 
</div>
<div class="quarto-title-author-email">
<a href="mailto:ylin0350@uni.sydney.edu.au">ylin0350@uni.sydney.edu.au</a>
</div>
</div>
</div>

</section>
<section id="problem-statement" class="slide level2">
<h2>Problem Statement</h2>
<p>Music genre classification is a multiclass supervised learning problem in which a model predicts the genre of a track from its measurable audio characteristics. This project uses the Spotify Tracks Dataset, which comprises 114,000 tracks spanning 114 genre categories, with track_genre as the classification target. Predictor variables include a range of audio and track-level features: popularity, duration, danceability, energy, loudness, speechiness, acousticness, instrumentalness, liveness, valence, and tempo.</p>
<p>The task is inherently difficult because genre boundaries are often acoustically ambiguous — tracks from different genres can exhibit similar distributions of tempo, energy, or danceability, making fine-grained separation challenging. Consequently, evaluation must go beyond aggregate accuracy to include class-level diagnostics that expose where and how the model fails.</p>
</section>
<section id="phase-2-objective" class="slide level2">
<h2>Phase 2 Objective</h2>
<p>The objective of Phase 2 is to implement the initial Random Forest classification model proposed in Phase 1. The model is trained using selected Spotify audio features and evaluated on a separate test set. The main evaluation metrics include accuracy and F1-score.</p>
<p>In addition to measuring overall performance, this phase also focuses on analysing the model’s prediction errors. A confusion matrix is used to identify which genres are correctly classified and which genres are frequently confused. This provides useful evidence for understanding the strengths and limitations of the initial model.</p>
</section>
<section id="link-to-phase-1-plan" class="slide level2">
<h2>Link to Phase 1 Plan</h2>
<p>Phase 2 directly follows the project plan developed in Phase 1. In Phase 1, Random Forest was selected as the main modelling approach, and evaluation metrics such as accuracy, F1-score, and confusion matrix analysis were planned. Phase 2 implements these planned tasks by training the initial model, evaluating its performance, and interpreting the classification results.</p>
<p>Overall, this phase provides the first experimental results of the project and forms the foundation for future model improvement and refinement.</p>
</section>
<section id="dataset-overview" class="slide level2">
<h2>Dataset Overview</h2>
<p>The Spotify Track Dataset was used in this project to predict the genre of a song based on its track-level and audio features. The response variable is <code>track_genre</code> which contains multiple genre categories. Therefore, this task is a multi-classifier task. The dataset obtains varies metadata includes numerical and descriptive data. Since the aim is to classify song based on measurable audio characteristcs, the model process would mainly focus on the numerical data.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href=""></a><span class="co"># Load data</span></span>
<span id="cb1-2"><a href=""></a>spotify_df <span class="sc">|&gt;</span> <span class="fu">dim</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 114000     21</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href=""></a>spotify_df <span class="sc">|&gt;</span> <span class="fu">str</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   114000 obs. of  21 variables:
 $ X               : int  0 1 2 3 4 5 6 7 8 9 ...
 $ track_id        : chr  "5SuOikwiRyPMVoIQDJUgSV" "4qPNDBW1i3p13qLCt0Ki3A" "1iJBSr7s7jYXzM8EGcbK5b" "6lfxq3CG4xtTiEg7opyCyx" ...
 $ artists         : chr  "Gen Hoshino" "Ben Woodward" "Ingrid Michaelson;ZAYN" "Kina Grannis" ...
 $ album_name      : chr  "Comedy" "Ghost (Acoustic)" "To Begin Again" "Crazy Rich Asians (Original Motion Picture Soundtrack)" ...
 $ track_name      : chr  "Comedy" "Ghost - Acoustic" "To Begin Again" "Can't Help Falling In Love" ...
 $ popularity      : int  73 55 57 71 82 58 74 80 74 56 ...
 $ duration_ms     : int  230666 149610 210826 201933 198853 214240 229400 242946 189613 205594 ...
 $ explicit        : chr  "False" "False" "False" "False" ...
 $ danceability    : num  0.676 0.42 0.438 0.266 0.618 0.688 0.407 0.703 0.625 0.442 ...
 $ energy          : num  0.461 0.166 0.359 0.0596 0.443 0.481 0.147 0.444 0.414 0.632 ...
 $ key             : int  1 1 0 0 2 6 2 11 0 1 ...
 $ loudness        : num  -6.75 -17.23 -9.73 -18.52 -9.68 ...
 $ mode            : int  0 1 1 1 1 1 1 1 1 1 ...
 $ speechiness     : num  0.143 0.0763 0.0557 0.0363 0.0526 0.105 0.0355 0.0417 0.0369 0.0295 ...
 $ acousticness    : num  0.0322 0.924 0.21 0.905 0.469 0.289 0.857 0.559 0.294 0.426 ...
 $ instrumentalness: num  1.01e-06 5.56e-06 0.00 7.07e-05 0.00 0.00 2.89e-06 0.00 0.00 4.19e-03 ...
 $ liveness        : num  0.358 0.101 0.117 0.132 0.0829 0.189 0.0913 0.0973 0.151 0.0735 ...
 $ valence         : num  0.715 0.267 0.12 0.143 0.167 0.666 0.0765 0.712 0.669 0.196 ...
 $ tempo           : num  87.9 77.5 76.3 181.7 119.9 ...
 $ time_signature  : int  4 4 4 3 4 4 3 4 4 4 ...
 $ track_genre     : chr  "acoustic" "acoustic" "acoustic" "acoustic" ...</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href=""></a>spotify_df <span class="sc">|&gt;</span> <span class="fu">head</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  X               track_id                artists
1 0 5SuOikwiRyPMVoIQDJUgSV            Gen Hoshino
2 1 4qPNDBW1i3p13qLCt0Ki3A           Ben Woodward
3 2 1iJBSr7s7jYXzM8EGcbK5b Ingrid Michaelson;ZAYN
4 3 6lfxq3CG4xtTiEg7opyCyx           Kina Grannis
5 4 5vjLSffimiIP26QG5WcN2K       Chord Overstreet
6 5 01MVOl9KtVTNfFiBU9I7dc           Tyrone Wells
                                              album_name
1                                                 Comedy
2                                       Ghost (Acoustic)
3                                         To Begin Again
4 Crazy Rich Asians (Original Motion Picture Soundtrack)
5                                                Hold On
6                                   Days I Will Remember
                  track_name popularity duration_ms explicit danceability
1                     Comedy         73      230666    False        0.676
2           Ghost - Acoustic         55      149610    False        0.420
3             To Begin Again         57      210826    False        0.438
4 Can't Help Falling In Love         71      201933    False        0.266
5                    Hold On         82      198853    False        0.618
6       Days I Will Remember         58      214240    False        0.688
  energy key loudness mode speechiness acousticness instrumentalness liveness
1 0.4610   1   -6.746    0      0.1430       0.0322         1.01e-06   0.3580
2 0.1660   1  -17.235    1      0.0763       0.9240         5.56e-06   0.1010
3 0.3590   0   -9.734    1      0.0557       0.2100         0.00e+00   0.1170
4 0.0596   0  -18.515    1      0.0363       0.9050         7.07e-05   0.1320
5 0.4430   2   -9.681    1      0.0526       0.4690         0.00e+00   0.0829
6 0.4810   6   -8.807    1      0.1050       0.2890         0.00e+00   0.1890
  valence   tempo time_signature track_genre
1   0.715  87.917              4    acoustic
2   0.267  77.489              4    acoustic
3   0.120  76.332              4    acoustic
4   0.143 181.740              3    acoustic
5   0.167 119.949              4    acoustic
6   0.666  98.017              4    acoustic</code></pre>
</div>
</div>
</section>
<section id="features-and-response-variable" class="slide level2">
<h2>Features and Response Variable</h2>
<ul>
<li>track_id: The Spotify ID for the track</li>
<li>artists: The artists’ names who performed the track. If there is more than one artist, they are separated by a ;</li>
<li>album_name: The album name in which the track appears</li>
<li>track_name: Name of the track</li>
<li>popularity: The popularity of a track is a value between 0 and 100, with 100 being the most popular. The popularity is calculated by algorithm and is based, in the most part, on the total number of plays the track has had and how recent those plays are. Generally speaking, songs that are being played a lot now will have a higher popularity than songs that were played a lot in the past. Duplicate tracks (e.g.&nbsp;the same track from a single and an album) are rated independently. Artist and album popularity is derived mathematically from track popularity.</li>
<li>duration_ms: The track length in milliseconds</li>
<li>explicit: Whether or not the track has explicit lyrics (true = yes it does; false = no it does not OR unknown)</li>
<li>danceability: Danceability describes how suitable a track is for dancing based on a combination of musical elements including tempo, rhythm stability, beat strength, and overall regularity. A value of 0.0 is least danceable and 1.0 is most danceable</li>
<li>energy: Energy is a measure from 0.0 to 1.0 and represents a perceptual measure of intensity and activity. Typically, energetic tracks feel fast, loud, and noisy. For example, death metal has high energy, while a Bach prelude scores low on the scale</li>
<li>key: The key the track is in. Integers map to pitches using standard Pitch Class notation. E.g. 0 = C, 1 = C♯/D♭, 2 = D, and so on. If no key was detected, the value is -1</li>
<li>loudness: The overall loudness of a track in decibels (dB)</li>
<li>mode: Mode indicates the modality (major or minor) of a track, the type of scale from which its melodic content is derived. Major is represented by 1 and minor is 0</li>
<li>speechiness: Speechiness detects the presence of spoken words in a track. The more exclusively speech-like the recording (e.g.&nbsp;talk show, audio book, poetry), the closer to 1.0 the attribute value. Values above 0.66 describe tracks that are probably made entirely of spoken words. Values between 0.33 and 0.66 describe tracks that may contain both music and speech, either in sections or layered, including such cases as rap music. Values below 0.33 most likely represent music and other non-speech-like tracks</li>
<li>acousticness: A confidence measure from 0.0 to 1.0 of whether the track is acoustic. 1.0 represents high confidence the track is acoustic</li>
<li>instrumentalness: Predicts whether a track contains no vocals. “Ooh” and “aah” sounds are treated as instrumental in this context. Rap or spoken word tracks are clearly “vocal”. The closer the instrumentalness value is to 1.0, the greater likelihood the track contains no vocal content</li>
<li>liveness: Detects the presence of an audience in the recording. Higher liveness values represent an increased probability that the track was performed live. A value above 0.8 provides strong likelihood that the track is live</li>
<li>valence: A measure from 0.0 to 1.0 describing the musical positiveness conveyed by a track. Tracks with high valence sound more positive (e.g.&nbsp;happy, cheerful, euphoric), while tracks with low valence sound more negative (e.g.&nbsp;sad, depressed, angry)</li>
<li>tempo: The overall estimated tempo of a track in beats per minute (BPM). In musical terminology, tempo is the speed or pace of a given piece and derives directly from the average beat duration</li>
<li>time_signature: An estimated time signature. The time signature (meter) is a notational convention to specify how many beats are in each bar (or measure). The time signature ranges from 3 to 7 indicating time signatures of 3/4, to 7/4.</li>
<li>track_genre: The genre in which the track belongs</li>
</ul>
</section>
<section id="exploratory-data-analysis-and-data-visualization" class="slide level2">
<h2>Exploratory Data Analysis and Data Visualization</h2>
<h4 id="missing-values">Missing Values</h4>
<p>The dataset contains no missing values, as confirmed by the following visualization.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href=""></a><span class="fu">vis_miss</span>(spotify_df, <span class="at">warn_large_data =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="OSTA5003-project-phase2_Yawei-XI_Yifeng-LIN_files/figure-revealjs/unnamed-chunk-3-1.png" width="960" class="r-stretch"></section>
<section id="exploratory-data-analysis-and-data-visualization---continued" class="slide level2">
<h2>Exploratory Data Analysis and Data Visualization - Continued</h2>
<h4 id="target-imbalance">Target Imbalance</h4>
<p>Analysis of the target variable, track_genre, reveals that there are 114 distinct categories. Each category contains exactly 1,000 sample instances. The data is perfectly balanced across all classes.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href=""></a>genre_counts <span class="ot">&lt;-</span> spotify_df <span class="sc">|&gt;</span> <span class="fu">count</span>(track_genre, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span>
<span id="cb8-2"><a href=""></a></span>
<span id="cb8-3"><a href=""></a><span class="fu">head</span>(genre_counts)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  track_genre    n
1    acoustic 1000
2    afrobeat 1000
3    alt-rock 1000
4 alternative 1000
5     ambient 1000
6       anime 1000</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href=""></a><span class="fu">tail</span>(genre_counts)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    track_genre    n
109       tango 1000
110      techno 1000
111      trance 1000
112    trip-hop 1000
113     turkish 1000
114 world-music 1000</code></pre>
</div>
</div>
</section>
<section id="exploratory-data-analysis-and-data-visualization---continued-1" class="slide level2">
<h2>Exploratory Data Analysis and Data Visualization - Continued</h2>
<h4 id="feature-distributions">Feature Distributions</h4>
<p>Danceability exhibits an approximately normal distribution, whereas speechiness is severely right-skewed.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href=""></a>dp_danceability <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(spotify_df, <span class="fu">aes</span>(<span class="at">x =</span> danceability)) <span class="sc">+</span></span>
<span id="cb12-2"><a href=""></a>                   <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">"lightblue"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb12-3"><a href=""></a>                   <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb12-4"><a href=""></a>                   <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Density Plot of Danceability"</span>, <span class="at">x =</span> <span class="st">"Danceability"</span>, <span class="at">y =</span> <span class="st">"Density"</span>)</span>
<span id="cb12-5"><a href=""></a><span class="fu">print</span>(dp_danceability)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="OSTA5003-project-phase2_Yawei-XI_Yifeng-LIN_files/figure-revealjs/unnamed-chunk-5-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href=""></a>dp_speechiness <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(spotify_df, <span class="fu">aes</span>(<span class="at">x =</span> speechiness)) <span class="sc">+</span></span>
<span id="cb13-2"><a href=""></a>                  <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">"salmon"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb13-3"><a href=""></a>                  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb13-4"><a href=""></a>                  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Density Plot of Speechiness (Right-Skewed)"</span>, <span class="at">x =</span> <span class="st">"Speechiness"</span>, <span class="at">y =</span> <span class="st">"Density"</span>)</span>
<span id="cb13-5"><a href=""></a><span class="fu">print</span>(dp_speechiness)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="OSTA5003-project-phase2_Yawei-XI_Yifeng-LIN_files/figure-revealjs/unnamed-chunk-6-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="exploratory-data-analysis-and-data-visualization---continued-2" class="slide level2">
<h2>Exploratory Data Analysis and Data Visualization - Continued</h2>
<h4 id="feature-correlation">Feature Correlation</h4>
<p>The heatmap illustrates the correlation between numeric features. Notably, energy and loudness exhibit a very high positive correlation.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href=""></a>numeric_features <span class="ot">&lt;-</span> spotify_df <span class="sc">|&gt;</span> <span class="fu">select</span>(danceability, energy, loudness, speechiness, acousticness, instrumentalness, liveness, valence, tempo)</span>
<span id="cb14-2"><a href=""></a>cor_matrix <span class="ot">&lt;-</span> <span class="fu">cor</span>(numeric_features, <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span>
<span id="cb14-3"><a href=""></a></span>
<span id="cb14-4"><a href=""></a><span class="fu">corrplot</span>(cor_matrix, </span>
<span id="cb14-5"><a href=""></a>         <span class="at">method =</span> <span class="st">"color"</span>,</span>
<span id="cb14-6"><a href=""></a>         <span class="at">type =</span> <span class="st">"upper"</span>,</span>
<span id="cb14-7"><a href=""></a>         <span class="at">addCoef.col =</span> <span class="st">"black"</span>,</span>
<span id="cb14-8"><a href=""></a>         <span class="at">diag =</span> <span class="cn">FALSE</span>,</span>
<span id="cb14-9"><a href=""></a>         <span class="at">tl.col =</span> <span class="st">"black"</span>,</span>
<span id="cb14-10"><a href=""></a>         <span class="at">number.cex =</span> <span class="fl">0.8</span>,</span>
<span id="cb14-11"><a href=""></a>         <span class="at">title =</span> <span class="st">"Correlation Heatmap of Features"</span>,</span>
<span id="cb14-12"><a href=""></a>         <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="OSTA5003-project-phase2_Yawei-XI_Yifeng-LIN_files/figure-revealjs/unnamed-chunk-7-1.png" width="960" class="r-stretch"></section>
<section id="feature-engineering" class="slide level2">
<h2>Feature Engineering</h2>
<h4 id="data-cleaning">Data Cleaning</h4>
<ul>
<li>In the original dataset, the first two columns are data entrys’ sequence ID and Spotify track ID, which are not informative for genre classification. These columns are removed.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href=""></a>spotify_df <span class="ot">&lt;-</span> spotify_df[, <span class="sc">-</span><span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>)]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li>The features with nominal data (<code>explicit</code>, <code>key</code>, <code>mode</code>, <code>time_signature</code>) and the response variable (<code>track_genre</code>) are converted to factors.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href=""></a>spotify_df<span class="sc">$</span>explicit       <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(spotify_df<span class="sc">$</span>explicit)</span>
<span id="cb16-2"><a href=""></a>spotify_df<span class="sc">$</span>key            <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(spotify_df<span class="sc">$</span>key)</span>
<span id="cb16-3"><a href=""></a>spotify_df<span class="sc">$</span>mode           <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(spotify_df<span class="sc">$</span>mode)</span>
<span id="cb16-4"><a href=""></a>spotify_df<span class="sc">$</span>time_signature <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(spotify_df<span class="sc">$</span>time_signature)</span>
<span id="cb16-5"><a href=""></a></span>
<span id="cb16-6"><a href=""></a>spotify_df<span class="sc">$</span>track_genre    <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(spotify_df<span class="sc">$</span>track_genre)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li>Duplicate entries are identified and removed to ensure data integrity.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href=""></a><span class="fu">sum</span>(<span class="fu">duplicated</span>(spotify_df))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 577</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href=""></a>spotify_df <span class="ot">&lt;-</span> spotify_df[<span class="sc">!</span><span class="fu">duplicated</span>(spotify_df), ]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li>Examining the first row and structure of the cleaned dataset confirms that the data types are correct and the dataset is ready for further steps.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href=""></a><span class="fu">head</span>(spotify_df, <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      artists album_name track_name popularity duration_ms explicit
1 Gen Hoshino     Comedy     Comedy         73      230666    False
  danceability energy key loudness mode speechiness acousticness
1        0.676  0.461   1   -6.746    0       0.143       0.0322
  instrumentalness liveness valence  tempo time_signature track_genre
1         1.01e-06    0.358   0.715 87.917              4    acoustic</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href=""></a><span class="fu">str</span>(spotify_df)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   113423 obs. of  19 variables:
 $ artists         : chr  "Gen Hoshino" "Ben Woodward" "Ingrid Michaelson;ZAYN" "Kina Grannis" ...
 $ album_name      : chr  "Comedy" "Ghost (Acoustic)" "To Begin Again" "Crazy Rich Asians (Original Motion Picture Soundtrack)" ...
 $ track_name      : chr  "Comedy" "Ghost - Acoustic" "To Begin Again" "Can't Help Falling In Love" ...
 $ popularity      : int  73 55 57 71 82 58 74 80 74 56 ...
 $ duration_ms     : int  230666 149610 210826 201933 198853 214240 229400 242946 189613 205594 ...
 $ explicit        : Factor w/ 2 levels "False","True": 1 1 1 1 1 1 1 1 1 1 ...
 $ danceability    : num  0.676 0.42 0.438 0.266 0.618 0.688 0.407 0.703 0.625 0.442 ...
 $ energy          : num  0.461 0.166 0.359 0.0596 0.443 0.481 0.147 0.444 0.414 0.632 ...
 $ key             : Factor w/ 12 levels "0","1","2","3",..: 2 2 1 1 3 7 3 12 1 2 ...
 $ loudness        : num  -6.75 -17.23 -9.73 -18.52 -9.68 ...
 $ mode            : Factor w/ 2 levels "0","1": 1 2 2 2 2 2 2 2 2 2 ...
 $ speechiness     : num  0.143 0.0763 0.0557 0.0363 0.0526 0.105 0.0355 0.0417 0.0369 0.0295 ...
 $ acousticness    : num  0.0322 0.924 0.21 0.905 0.469 0.289 0.857 0.559 0.294 0.426 ...
 $ instrumentalness: num  1.01e-06 5.56e-06 0.00 7.07e-05 0.00 0.00 2.89e-06 0.00 0.00 4.19e-03 ...
 $ liveness        : num  0.358 0.101 0.117 0.132 0.0829 0.189 0.0913 0.0973 0.151 0.0735 ...
 $ valence         : num  0.715 0.267 0.12 0.143 0.167 0.666 0.0765 0.712 0.669 0.196 ...
 $ tempo           : num  87.9 77.5 76.3 181.7 119.9 ...
 $ time_signature  : Factor w/ 5 levels "0","1","3","4",..: 4 4 4 3 4 4 3 4 4 4 ...
 $ track_genre     : Factor w/ 114 levels "acoustic","afrobeat",..: 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
</div>
</div>
<p>The features <code>explicit</code>, <code>key</code>, <code>mode</code>, and <code>time_signature</code> are now factors, while the numeric features remain as numeric types. The response variable <code>track_genre</code> is also a factor with 114 levels, corresponding to the unique genres in the dataset.</p>
</section>
<section id="feature-engineering---continued" class="slide level2">
<h2>Feature Engineering - Continued</h2>
<h4 id="data-transformation">Data Transformation</h4>
<ul>
<li>Scale the skewed features <code>speechiness</code> and <code>instrumentalness</code> using log transformation to reduce skewness and improve model performance.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href=""></a>spotify_df<span class="sc">$</span>speechiness      <span class="ot">&lt;-</span> <span class="fu">log1p</span>(spotify_df<span class="sc">$</span>speechiness)</span>
<span id="cb24-2"><a href=""></a>spotify_df<span class="sc">$</span>instrumentalness <span class="ot">&lt;-</span> <span class="fu">log1p</span>(spotify_df<span class="sc">$</span>instrumentalness)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li>The text features <code>artists</code>, <code>album_name</code>, <code>track_name</code> are not directly suitable for model input, but they contain rich metadata that can be transformed into informative features. For example, the length and complexity of track names may provide genre-specific signals. Binary indicators for the presence of featured artists, remixes, and live recordings can capture important stylistic cues. After extracting these new features, the original text columns are removed to avoid redundancy and reduce dimensionality.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href=""></a>spotify_df<span class="sc">$</span>name_length     <span class="ot">&lt;-</span> <span class="fu">nchar</span>(spotify_df<span class="sc">$</span>track_name)</span>
<span id="cb25-2"><a href=""></a>spotify_df<span class="sc">$</span>name_word_count <span class="ot">&lt;-</span> <span class="fu">lengths</span>(<span class="fu">strsplit</span>(spotify_df<span class="sc">$</span>track_name, <span class="st">"</span><span class="sc">\\</span><span class="st">s+"</span>))</span>
<span id="cb25-3"><a href=""></a>spotify_df<span class="sc">$</span>has_feat        <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(<span class="fu">grepl</span>(<span class="st">"feat</span><span class="sc">\\</span><span class="st">.|ft</span><span class="sc">\\</span><span class="st">."</span>, spotify_df<span class="sc">$</span>track_name, <span class="at">ignore.case=</span><span class="cn">TRUE</span>))</span>
<span id="cb25-4"><a href=""></a>spotify_df<span class="sc">$</span>is_remix        <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(<span class="fu">grepl</span>(<span class="st">"remix|edit|mix"</span>, spotify_df<span class="sc">$</span>track_name, <span class="at">ignore.case=</span><span class="cn">TRUE</span>))</span>
<span id="cb25-5"><a href=""></a>spotify_df<span class="sc">$</span>is_live         <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(<span class="fu">grepl</span>(<span class="st">"live|concert"</span>, spotify_df<span class="sc">$</span>track_name, <span class="at">ignore.case=</span><span class="cn">TRUE</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href=""></a>spotify_df<span class="sc">$</span>album_is_single <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(<span class="fu">grepl</span>(<span class="st">"single|ep"</span>, spotify_df<span class="sc">$</span>album_name, <span class="at">ignore.case=</span><span class="cn">TRUE</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li>The <code>artists</code> feature can be transformed into a frequency-based feature. Certain artists may be strongly associated with specific genres. However, in this dataset, such a transformation may introduce data leakage issue. Therefore, <code>artists</code> feature is directly removed without transformation.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href=""></a>artist_freq <span class="ot">&lt;-</span> <span class="fu">table</span>(spotify_df<span class="sc">$</span>artists)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li>Finally, the original text features <code>artists</code>, <code>album_name</code>, <code>track_name</code> are removed as they are not suitable for direct model input.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href=""></a>spotify_df <span class="ot">&lt;-</span> spotify_df[, <span class="sc">!</span>(<span class="fu">names</span>(spotify_df) <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"artists"</span>, <span class="st">"album_name"</span>, <span class="st">"track_name"</span>))]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Examining the first row and structure of the transformed dataset confirms that the new features have been successfully created and the original text columns have been removed.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href=""></a><span class="fu">head</span>(spotify_df, <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  popularity duration_ms explicit danceability energy key loudness mode
1         73      230666    False        0.676  0.461   1   -6.746    0
  speechiness acousticness instrumentalness liveness valence  tempo
1   0.1336564       0.0322     1.009999e-06    0.358   0.715 87.917
  time_signature track_genre name_length name_word_count has_feat is_remix
1              4    acoustic           6               1        0        0
  is_live album_is_single
1       0               0</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href=""></a><span class="fu">str</span>(spotify_df)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   113423 obs. of  22 variables:
 $ popularity      : int  73 55 57 71 82 58 74 80 74 56 ...
 $ duration_ms     : int  230666 149610 210826 201933 198853 214240 229400 242946 189613 205594 ...
 $ explicit        : Factor w/ 2 levels "False","True": 1 1 1 1 1 1 1 1 1 1 ...
 $ danceability    : num  0.676 0.42 0.438 0.266 0.618 0.688 0.407 0.703 0.625 0.442 ...
 $ energy          : num  0.461 0.166 0.359 0.0596 0.443 0.481 0.147 0.444 0.414 0.632 ...
 $ key             : Factor w/ 12 levels "0","1","2","3",..: 2 2 1 1 3 7 3 12 1 2 ...
 $ loudness        : num  -6.75 -17.23 -9.73 -18.52 -9.68 ...
 $ mode            : Factor w/ 2 levels "0","1": 1 2 2 2 2 2 2 2 2 2 ...
 $ speechiness     : num  0.1337 0.0735 0.0542 0.0357 0.0513 ...
 $ acousticness    : num  0.0322 0.924 0.21 0.905 0.469 0.289 0.857 0.559 0.294 0.426 ...
 $ instrumentalness: num  1.01e-06 5.56e-06 0.00 7.07e-05 0.00 ...
 $ liveness        : num  0.358 0.101 0.117 0.132 0.0829 0.189 0.0913 0.0973 0.151 0.0735 ...
 $ valence         : num  0.715 0.267 0.12 0.143 0.167 0.666 0.0765 0.712 0.669 0.196 ...
 $ tempo           : num  87.9 77.5 76.3 181.7 119.9 ...
 $ time_signature  : Factor w/ 5 levels "0","1","3","4",..: 4 4 4 3 4 4 3 4 4 4 ...
 $ track_genre     : Factor w/ 114 levels "acoustic","afrobeat",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ name_length     : int  6 16 14 26 7 20 13 9 5 6 ...
 $ name_word_count : int  1 3 3 5 2 4 2 2 1 1 ...
 $ has_feat        : int  0 0 0 0 0 0 0 0 0 0 ...
 $ is_remix        : int  0 0 0 0 0 0 0 0 0 0 ...
 $ is_live         : int  0 0 0 0 0 0 0 0 0 0 ...
 $ album_is_single : int  0 0 0 0 0 0 0 0 0 0 ...</code></pre>
</div>
</div>
</section>
<section id="feature-engineering---continued-1" class="slide level2">
<h2>Feature Engineering - Continued</h2>
<h4 id="pca">PCA</h4>
<ul>
<li>The number of principal components to retain is determined by two complementary criteria.Inspecting the summary(pca_result) output above, the cumulative proportion of variance reaches [X]% at PC7, satisfying both criteria. PC8 through PC10 each contribute less than 5% additional variance and likely capture measurement noise rather than meaningful acoustic signal. Therefore, the first seven principal components (PC1–PC7) are extracted and substituted for the original ten audio features in all subsequent modelling steps.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href=""></a>pca_features <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"danceability"</span>, <span class="st">"duration_ms"</span>, <span class="st">"energy"</span>, </span>
<span id="cb33-2"><a href=""></a>                  <span class="st">"loudness"</span>,  <span class="st">"speechiness"</span>, <span class="st">"acousticness"</span>, </span>
<span id="cb33-3"><a href=""></a>                  <span class="st">"instrumentalness"</span>, <span class="st">"liveness"</span>, <span class="st">"valence"</span>, <span class="st">"tempo"</span>)</span>
<span id="cb33-4"><a href=""></a>pca_data <span class="ot">&lt;-</span> spotify_df[, pca_features]</span>
<span id="cb33-5"><a href=""></a>pca_data <span class="ot">&lt;-</span> pca_data <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span><span class="fu">ifelse</span>(<span class="fu">is.na</span>(.), <span class="fu">mean</span>(., <span class="at">na.rm =</span> <span class="cn">TRUE</span>), .)))</span>
<span id="cb33-6"><a href=""></a>pca_data <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(pca_data)</span>
<span id="cb33-7"><a href=""></a></span>
<span id="cb33-8"><a href=""></a>pca_result <span class="ot">&lt;-</span> <span class="fu">prcomp</span>(pca_data, <span class="at">center =</span> <span class="cn">TRUE</span>, <span class="at">scale. =</span> <span class="cn">TRUE</span>)</span>
<span id="cb33-9"><a href=""></a></span>
<span id="cb33-10"><a href=""></a><span class="fu">summary</span>(pca_result)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Importance of components:
                          PC1    PC2    PC3    PC4     PC5     PC6     PC7
Standard deviation     1.6939 1.2375 1.1030 0.9844 0.94896 0.91410 0.86453
Proportion of Variance 0.2869 0.1532 0.1216 0.0969 0.09005 0.08356 0.07474
Cumulative Proportion  0.2869 0.4401 0.5617 0.6586 0.74867 0.83223 0.90697
                           PC8     PC9    PC10
Standard deviation     0.68021 0.57160 0.37530
Proportion of Variance 0.04627 0.03267 0.01408
Cumulative Proportion  0.95324 0.98592 1.00000</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href=""></a><span class="fu">round</span>(pca_result<span class="sc">$</span>rotation[, <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>], <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    PC1    PC2    PC3    PC4    PC5    PC6    PC7    PC8    PC9
danceability     -0.246 -0.481 -0.231  0.389  0.255 -0.075  0.144 -0.619 -0.061
duration_ms       0.016  0.404 -0.202  0.550 -0.110 -0.664 -0.179  0.092 -0.017
energy           -0.509  0.265  0.030  0.057  0.001  0.182  0.099  0.228 -0.180
loudness         -0.516  0.077 -0.045 -0.045 -0.177  0.103 -0.166 -0.061 -0.620
speechiness      -0.122 -0.083  0.588  0.275  0.588  0.034 -0.406  0.181  0.041
acousticness      0.437 -0.316  0.184 -0.112 -0.031 -0.288 -0.049  0.087 -0.692
instrumentalness  0.278  0.330 -0.158  0.246  0.468  0.259  0.556  0.119 -0.291
liveness         -0.086  0.145  0.700  0.085 -0.298 -0.184  0.512 -0.289  0.038
valence          -0.296 -0.486 -0.077  0.010  0.015 -0.298  0.406  0.612  0.110
tempo            -0.189  0.238 -0.058 -0.621  0.487 -0.486  0.078 -0.199  0.009
                   PC10
danceability      0.158
duration_ms      -0.013
energy            0.735
loudness         -0.516
speechiness      -0.100
acousticness      0.299
instrumentalness -0.187
liveness         -0.071
valence          -0.171
tempo             0.007</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href=""></a>pc_extracted <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(pca_result<span class="sc">$</span>x[, <span class="dv">1</span><span class="sc">:</span><span class="dv">7</span>])</span>
<span id="cb37-2"><a href=""></a>df_reduced <span class="ot">&lt;-</span> spotify_df[, <span class="sc">!</span>(<span class="fu">names</span>(spotify_df) <span class="sc">%in%</span> pca_features)]</span>
<span id="cb37-3"><a href=""></a>spotify_df <span class="ot">&lt;-</span> <span class="fu">cbind</span>(df_reduced, pc_extracted)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li>The following illustrates the dataset after PCA.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href=""></a><span class="fu">head</span>(spotify_df, <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  popularity explicit key mode time_signature track_genre name_length
1         73    False   1    0              4    acoustic           6
  name_word_count has_feat is_remix is_live album_is_single        PC1
1               1        0        0       0               0 -0.6637963
        PC2       PC3      PC4        PC5       PC6       PC7
1 -1.032581 0.6648634 1.141573 -0.4788758 0.1090471 0.1184252</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href=""></a><span class="fu">str</span>(spotify_df)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   113423 obs. of  19 variables:
 $ popularity     : int  73 55 57 71 82 58 74 80 74 56 ...
 $ explicit       : Factor w/ 2 levels "False","True": 1 1 1 1 1 1 1 1 1 1 ...
 $ key            : Factor w/ 12 levels "0","1","2","3",..: 2 2 1 1 3 7 3 12 1 2 ...
 $ mode           : Factor w/ 2 levels "0","1": 1 2 2 2 2 2 2 2 2 2 ...
 $ time_signature : Factor w/ 5 levels "0","1","3","4",..: 4 4 4 3 4 4 3 4 4 4 ...
 $ track_genre    : Factor w/ 114 levels "acoustic","afrobeat",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ name_length    : int  6 16 14 26 7 20 13 9 5 6 ...
 $ name_word_count: int  1 3 3 5 2 4 2 2 1 1 ...
 $ has_feat       : int  0 0 0 0 0 0 0 0 0 0 ...
 $ is_remix       : int  0 0 0 0 0 0 0 0 0 0 ...
 $ is_live        : int  0 0 0 0 0 0 0 0 0 0 ...
 $ album_is_single: int  0 0 0 0 0 0 0 0 0 0 ...
 $ PC1            : num  -0.664 3.323 1.399 3.399 0.999 ...
 $ PC2            : num  -1.033 -1.331 0.149 0.302 -0.318 ...
 $ PC3            : num  0.665 0.494 -0.12 0.268 -0.427 ...
 $ PC4            : num  1.142 -0.242 0.292 -2.599 -0.361 ...
 $ PC5            : num  -0.479 -0.71 -1.133 0.422 -0.139 ...
 $ PC6            : num  0.109 0.431 1.118 -1.511 0.223 ...
 $ PC7            : num  0.118 -0.982 -1.233 -0.847 -0.959 ...</code></pre>
</div>
</div>
</section>
<section id="train-test-split" class="slide level2">
<h2>Train-Test Split</h2>
<p>The dataset was split into training and testing sets using an 80/20 ratio, ensuring that the distribution of genres is preserved in both sets.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href=""></a><span class="fu">set.seed</span>(<span class="dv">5003</span>)</span>
<span id="cb42-2"><a href=""></a></span>
<span id="cb42-3"><a href=""></a>train_idx <span class="ot">&lt;-</span> <span class="fu">createDataPartition</span>(spotify_df<span class="sc">$</span>track_genre, <span class="at">p =</span> <span class="fl">0.8</span>, <span class="at">list =</span> <span class="cn">FALSE</span>)</span>
<span id="cb42-4"><a href=""></a>train_df  <span class="ot">&lt;-</span> spotify_df[train_idx, ]</span>
<span id="cb42-5"><a href=""></a>test_df   <span class="ot">&lt;-</span> spotify_df[<span class="sc">-</span>train_idx, ]</span>
<span id="cb42-6"><a href=""></a></span>
<span id="cb42-7"><a href=""></a><span class="fu">cat</span>(<span class="st">"Train size:"</span>, <span class="fu">nrow</span>(train_df), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Train size: 90793 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href=""></a><span class="fu">cat</span>(<span class="st">"Test size: "</span>, <span class="fu">nrow</span>(test_df),  <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Test size:  22630 </code></pre>
</div>
</div>
</section>
<section id="model-justification---random-forest" class="slide level2">
<h2>Model Justification - Random Forest</h2>
<p>Random Forest was selected as the main classification method. It is an ensemble learning method that builds multiple decision trees and combines their prediction to produce a final classification result.</p>
<p>Compare with single decision tree, Random Forest can reduce overfitting and improve model stability.</p>
<p>This model is suitable for the Spotify genre classification task because the target variable <code>track_genre</code> contains multiple genre categories. Random Forest can handle multiclass classification directly can capture non-linear relationships between audio features and music genres.</p>
</section>
<section id="model-training" class="slide level2">
<h2>Model Training</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href=""></a><span class="co"># set.seed(5003)</span></span>
<span id="cb46-2"><a href=""></a></span>
<span id="cb46-3"><a href=""></a><span class="co"># rf_formula &lt;- track_genre ~.</span></span>
<span id="cb46-4"><a href=""></a></span>
<span id="cb46-5"><a href=""></a><span class="co"># rf_model&lt;-ranger(</span></span>
<span id="cb46-6"><a href=""></a><span class="co">#   formula = rf_formula,</span></span>
<span id="cb46-7"><a href=""></a><span class="co">#   data = train_dat,</span></span>
<span id="cb46-8"><a href=""></a><span class="co">#   num.trees = 300,</span></span>
<span id="cb46-9"><a href=""></a><span class="co">#   mtry = floor(sqrt(ncol(train_dat) - 1)),</span></span>
<span id="cb46-10"><a href=""></a><span class="co">#   min.node.size = 5,</span></span>
<span id="cb46-11"><a href=""></a><span class="co">#   importance = "impurity",</span></span>
<span id="cb46-12"><a href=""></a><span class="co">#   classification = TRUE</span></span>
<span id="cb46-13"><a href=""></a><span class="co"># )</span></span>
<span id="cb46-14"><a href=""></a></span>
<span id="cb46-15"><a href=""></a><span class="co"># rf_model</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="hyperparameter-tunning" class="slide level2">
<h2>Hyperparameter Tunning</h2>
<p>Tree number is a critical hyperparameter for Random Forest. A grid search was conducted over a range of tree numbers (50, 100, 200, 300, 400, 500, 600, 800) to identify the optimal value that maximizes out-of-bag (OOB) accuracy.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href=""></a>rf_model <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb47-2"><a href=""></a></span>
<span id="cb47-3"><a href=""></a>tree_grid <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">50</span>, <span class="dv">100</span>, <span class="dv">200</span>, <span class="dv">300</span>, <span class="dv">400</span>, <span class="dv">500</span>, <span class="dv">600</span>, <span class="dv">800</span>)</span>
<span id="cb47-4"><a href=""></a>tree_results <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">num.trees =</span> tree_grid, <span class="at">oob_accuracy =</span> <span class="cn">NA</span>)</span>
<span id="cb47-5"><a href=""></a></span>
<span id="cb47-6"><a href=""></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq_along</span>(tree_grid)) {</span>
<span id="cb47-7"><a href=""></a>  m <span class="ot">&lt;-</span> <span class="fu">ranger</span>(</span>
<span id="cb47-8"><a href=""></a>    <span class="at">formula        =</span> track_genre <span class="sc">~</span> .,</span>
<span id="cb47-9"><a href=""></a>    <span class="at">data           =</span> train_df,</span>
<span id="cb47-10"><a href=""></a>    <span class="at">num.trees      =</span> tree_grid[i],</span>
<span id="cb47-11"><a href=""></a>    <span class="at">mtry           =</span> <span class="fu">floor</span>(<span class="fu">sqrt</span>(<span class="fu">ncol</span>(train_df) <span class="sc">-</span> <span class="dv">1</span>)),</span>
<span id="cb47-12"><a href=""></a>    <span class="at">min.node.size  =</span> <span class="dv">5</span>,</span>
<span id="cb47-13"><a href=""></a>    <span class="at">classification =</span> <span class="cn">TRUE</span></span>
<span id="cb47-14"><a href=""></a>  )</span>
<span id="cb47-15"><a href=""></a></span>
<span id="cb47-16"><a href=""></a>  tree_results<span class="sc">$</span>oob_accuracy[i] <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> m<span class="sc">$</span>prediction.error</span>
<span id="cb47-17"><a href=""></a></span>
<span id="cb47-18"><a href=""></a>  <span class="cf">if</span> (<span class="fu">is.null</span>(rf_model) <span class="sc">||</span> (<span class="dv">1</span> <span class="sc">-</span> m<span class="sc">$</span>prediction.error) <span class="sc">&gt;</span> <span class="fu">max</span>(tree_results<span class="sc">$</span>oob_accuracy[<span class="sc">-</span>i], <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) {</span>
<span id="cb47-19"><a href=""></a>    rf_model <span class="ot">&lt;-</span> m</span>
<span id="cb47-20"><a href=""></a>  }</span>
<span id="cb47-21"><a href=""></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Growing trees.. Progress: 66%. Estimated remaining time: 16 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 41 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 8 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 1 minute, 5 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 33 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 1 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 1 minute, 33 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 58 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 27 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 1 minute, 55 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 1 minute, 19 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 47 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 16 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 2 minutes, 36 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 2 minutes, 4 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 1 minute, 33 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 1 minute, 2 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 31 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href=""></a><span class="fu">print</span>(tree_results)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  num.trees oob_accuracy
1        50    0.2630709
2       100    0.2807485
3       200    0.2900664
4       300    0.2936240
5       400    0.2959700
6       500    0.2975450
7       600    0.2975450
8       800    0.2991971</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href=""></a><span class="fu">ggplot</span>(tree_results, <span class="fu">aes</span>(<span class="at">x =</span> num.trees, <span class="at">y =</span> oob_accuracy)) <span class="sc">+</span></span>
<span id="cb51-2"><a href=""></a><span class="fu">geom_line</span>() <span class="sc">+</span> </span>
<span id="cb51-3"><a href=""></a><span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb51-4"><a href=""></a><span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"OOB Accuracy vs Number of Trees"</span>,</span>
<span id="cb51-5"><a href=""></a>     <span class="at">x =</span> <span class="st">"Number of Trees"</span>,</span>
<span id="cb51-6"><a href=""></a>     <span class="at">y =</span> <span class="st">"OOB Accuracy"</span>) <span class="sc">+</span></span>
<span id="cb51-7"><a href=""></a><span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href=""></a>best_trees <span class="ot">&lt;-</span> tree_results<span class="sc">$</span>num.trees[<span class="fu">which.max</span>(tree_results<span class="sc">$</span>oob_accuracy)]</span>
<span id="cb52-2"><a href=""></a><span class="fu">cat</span>(<span class="st">"Best num.trees:"</span>, best_trees, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Best num.trees: 800 </code></pre>
</div>
</div>
<img data-src="OSTA5003-project-phase2_Yawei-XI_Yifeng-LIN_files/figure-revealjs/unnamed-chunk-23-1.png" width="960" class="r-stretch"></section>
<section id="evaluation" class="slide level2">
<h2>Evaluation</h2>
<p>After the Random Forest model was trained, it was used to generate predictions on the testing dataset. The testing dataset was not used during model training, so it provides a more reliable way to evaluate how well the model performs on unseen data.</p>
<p>The prediction was generated using the <code>predict()</code> function:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href=""></a>rf_pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(rf_model, <span class="at">data =</span> test_df)</span>
<span id="cb54-2"><a href=""></a>  </span>
<span id="cb54-3"><a href=""></a>rf_cm <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(rf_pred<span class="sc">$</span>predictions, test_df<span class="sc">$</span>track_genre)</span>
<span id="cb54-4"><a href=""></a>rf_cm<span class="sc">$</span>overall</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Accuracy          Kappa  AccuracyLower  AccuracyUpper   AccuracyNull 
   0.303711887    0.297548764    0.297723870    0.309750355    0.008837826 
AccuracyPValue  McnemarPValue 
   0.000000000            NaN </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href=""></a><span class="fu">mean</span>(rf_cm<span class="sc">$</span>byClass[, <span class="st">"F1"</span>], <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2947608</code></pre>
</div>
</div>
</section>
<section id="discussion" class="slide level2">
<h2>Discussion</h2>
<p>The tuned Random Forest model achieved a test accuracy of 30.4% and a macro F1-score of 0.295 across 114 genre classes. These figures must be interpreted in context: a random baseline classifier would achieve only 0.88% accuracy (1/114), meaning the model performs approximately 34 times better than chance.</p>
<p>The Kappa value of 0.298 indicates “Fair” agreement, which is a meaningful result given the extreme difficulty of 114-class classification with high-level audio summary features.</p>
</section>
<section id="future-work" class="slide level2">
<h2>Future Work</h2>
<p>The current phase establishes a baseline Random Forest model. Several directions are planned for the final report:</p>
<ul>
<li><p>XGBoost: An XGBoost classifier will be trained and evaluated alongside Random Forest. XGBoost’s gradient boosting framework and regularisation are expected to outperform the baseline, particularly for acoustically ambiguous genre pairs identified in the error analysis.</p></li>
<li><p>Feature engineering refinement: Additional transformations — including PCA on log-transformed skewed features and threshold-based binary indicators derived from Spotify’s documented feature semantics — will be incorporated and their impact on classification performance assessed.</p></li>
<li><p>Model comparison and selection: A unified comparison table of accuracy, macro F1-score, and Kappa across all models will be presented in the final report to support a data-driven model selection decision.</p></li>
</ul>
</section>
<section id="conclusion" class="slide level2">
<h2>Conclusion</h2>
<p>In this phase, we implemented the initial Random Forest model for classifying Spotify tracks into genres based on their audio features. The model was trained on the training dataset and evaluated on a separate test set using accuracy and F1-score as evaluation metrics. The results provide insights into the model’s performance and highlight areas for improvement in future phases.</p>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="OSTA5003-project-phase2_Yawei XI_Yifeng LIN_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="OSTA5003-project-phase2_Yawei XI_Yifeng LIN_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="OSTA5003-project-phase2_Yawei XI_Yifeng LIN_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="OSTA5003-project-phase2_Yawei XI_Yifeng LIN_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="OSTA5003-project-phase2_Yawei XI_Yifeng LIN_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="OSTA5003-project-phase2_Yawei XI_Yifeng LIN_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="OSTA5003-project-phase2_Yawei XI_Yifeng LIN_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="OSTA5003-project-phase2_Yawei XI_Yifeng LIN_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="OSTA5003-project-phase2_Yawei XI_Yifeng LIN_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="OSTA5003-project-phase2_Yawei XI_Yifeng LIN_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: false,

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 20000,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    <style>
        .reveal {
            font-family: 'Times New Roman', Times, serif; font-size: 10pt !important;;
        }
        .reveal h1, .reveal h2, .reveal h3 {
            font-family: Helvetica, Arial, sans-serif !important;;
        }
        .reveal code, .reveal pre {
            font-family: 'Courier New', Courier, monospace !important;;
        }
    </style>
    

</body></html>